### PR TITLE
renaming all the .css.scsses

### PR DESCRIPTION
**Pull request by Dfenniak**

### CODE REVIEW

**Comment by Dfenniak** [comment]
PTAL

**Comment by X0nic** [comment]
I think the could potentially break older versions of rails, but I can't seem to find what version.

**Comment by X0nic** [comment]
I say we bump the major (minor maybe) version and lock sass-rails to  ">= 4.0"

**Comment by Dfenniak** [comment]
I'm into that too

**Comment by X0nic** [comment]
Not sure of the process here, but I have bumped sass rails. Should I bump the gem version here, or once it is in master?

**Comment by Dfenniak** [comment]
LGTM

**Pull request merged**
