### PR TITLE
Support of Rails 5.2

### PR DESCRIPTION
**Pull request by fwininger**
This branch works with Rails 5.2

### CODE REVIEW

**Comment by CodingAnarchy** [comment]
I don't think this repository is maintained any longer by @nathany, etc.  But thanks for the branch that I can use as well.

**Comment by fwininger** [comment]
I'm happy if it can help you.

**Comment by nathany** [comment]
@CodingAnarchy I no longer work at GetJobber, but perhaps someone who does will help maintain this. Cheers.

**Comment by tophernuts** [comment]
Closed by https://github.com/GetJobber/recurring_select/pull/122

Thanks for your help though! 🎉

**Pull request closed without merging**
