### PR TITLE
Added until and indefinite until with configuration

### PR DESCRIPTION
**Pull request by emilkarl**
Based on #61 PR and @findchris work I forked and added option to include until and indefinite until.

I also updated so it works with the latest master from GetJobber.

### CODE REVIEW

**Comment by findchris** [comment]
Nice :clap: - This functionality definitely needs to be incorporated.

**Comment by emilkarl** [comment]
Someone should really clean upp the styles as well so it can easily be overridden. I will try to do it some day.

**Comment by emilkarl** [comment]
Add possibility to disable outerCancel

```
$.fn.recurring_select.options = {
  monthly: {
    show_week: [true, true, true, true, false, false]
  },
  until: true,
  indefinite_until: true,
  datepicker: {
    firstDay: 1  # 1 = monday, 0 = sunday
  },
  close_on_outside_click: true
}
```

**Comment by emilkarl** [comment]
Added ability to set the beforeShowDay function on the datepicker

**Comment by nfedyashev** [comment]
@emilkarl thanks a lot!

**Comment by briantigerchow** [comment]
The date picker and display element are broken. The day and month are mixed up.

pasted_image_6_8_16__6_19_pm

**Comment by emilkarl** [comment]
Hmm Strange. Might have something to do the datepicker_format. I havent seen this before but as you can see the default datepicker_format is Y-m-d here: https://github.com/GetJobber/recurring_select/pull/96/files#diff-259648c56ceac4822cff1057c8c1ee9eL5

I dont have time to look at it right away.

**Comment by briantigerchow** [comment]
I think this can be fixed in two steps. 

1) change the default date picker_format. 

2) Fix an issue with `Time.zone.parse` in `RecurringSelect.filter_params` as I have done here: https://github.com/briantigerchow/recurring_select/commit/bbc430b7c378ecc43a7a1c692e1790cad7170cfd

Together, these two changes fix the date-month-mixed-up issue for me.

**Comment by bhushangahire** [comment]
Not sure if this is merged or not. But is there a way to add until field now?

**Comment by emilkarl** [comment]
Wanna close this? :D

**Pull request closed without merging**
